### ISSUE TITLE
翻译偶尔会出现秘钥不正确

### ISSUE THREAD

**Issue by wushuai111** [maybeLab/bob-plugin-volc#1]
例如

Save copy/paste and command history to disk

**Comment by shoyuf** [comment]
已跟踪到问题，将于近日解决发布新版本

**Comment by shoyuf** [comment]
> 例如
> 
> Save copy/paste and command history to disk

已修复，请下载 1.0.2 版本
https://github.com/maybeLab/bob-plugin-volc/releases
