### ISSUE TITLE
插件填写token后 仍然无法使用

### ISSUE THREAD

**Issue by macoswk** [maybeLab/bob-plugin-volc#2]
![image](https://user-images.githubusercontent.com/86730293/164966800-59931dc4-ab1b-4cc5-9d69-12aa68a318fe.png)

**Comment by shoyuf** [comment]
![image](https://user-images.githubusercontent.com/27998490/164969701-64904a44-ae7f-433c-85bd-a3733ebcdd52.png)
我这边看上去没有问题，试试更新Bob和插件的版本
我的Bob版本为0.8.1，插件版本为1.0.1

**Comment by macoswk** [comment]
发现是mac系统版本的问题,之前是10.14.6 现在升级到 10.15.7就没问题了
